# Generated by Django 4.0 on 2021-12-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8000)),
            ],
        ),
    ]
