# Generated by Django 4.0 on 2021-12-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_options',
            field=models.CharField(choices=[('PAYPAL', 'paypal'), ('CARD', 'card')], default='paypal', max_length=100),
        ),
    ]
