# Generated by Django 4.0 on 2021-12-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentmethod_payment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='price_rate',
        ),
    ]
