# Generated by Django 4.0 on 2021-12-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_level', models.CharField(choices=[('HIGH SCHOOL', 'High School'), ('COLLEGE', 'College'), ('UNDERGRADUATE', 'Undergraduate'), ('MASTERS', 'Masters')], max_length=100)),
                ('task_type', models.CharField(choices=[('ESSAY', 'Essay'), ('REPORT', 'Report'), ('CASE STUDY', 'Case Study')], max_length=100)),
                ('task_pages', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=250)),
                ('task_description', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('task_files', models.FileField(blank=True, null=True, upload_to='media/')),
                ('task_images', models.ImageField(blank=True, null=True, upload_to='task/images/')),
                ('task_resources', models.URLField(blank=True, max_length=250, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
